###
GET http://localhost:9000/api/authentication HTTP/1.1

Content-Type: application/json
{
    "usuario" : "admin",
    "clave"  : "1234"
}

###
GET http://localhost:9000/api/menu HTTP/1.1

Content-Type: application/json

{
    "idusuario" : "1"
}

###
GET http://localhost:9000/api/getGen_usuarios  HTTP/1.1

###
POST http://localhost:9000/api HTTP/1.1
Content-Type: application/json

{
    "titulo" : "LIBRO 1 ",
    "autor"  : "ERNESTO GARCIA",
    "edicion": 3,
    "fecha": "1976-05-25",
    "numerico" : 45
}

###
POST http://localhost:9000/api/postGen_usuarios HTTP/1.1
Content-Type: application/json

{ 
        "nombre" : 'Ernesto'
       
} 
###
DELETE  http://localhost:9000/api/3 HTTP/1.1
Content-Type: application/json



###
PUT  http://localhost:9000/api/1 HTTP/1.1
Content-Type: application/json

{
    "titulo" : "ACTUALIZADO ",
    "autor"  : "UPDATE LIBRO",
    "edicion": 3,
    "fecha": "1976-05-25",
    "numerico" : 45
}

###
GET http://localhost:9000/api/call2 HTTP/1.1
Content-Type: application/json

{
    "titulo" : "",
    "autor"  : "Stephen garcia",
    "edicion": ""

}
